# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Workflow Test

on:
  push:
    branches: [ "new-ci-test" ]
  pull_request:
    branches: [ "new-ci-test" ]
    
jobs:
  run_on_specific_word:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message
        run: |
          # Extract the commit message from the last commit
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          
          # Check if the commit message contains a specific word
          if [[ $COMMIT_MESSAGE == *"build_docker"* ]]; then
            echo "Running workflow due to the specific word in the commit message."
          else
            echo "No specific word found in the commit message. Exiting workflow."
            exit 78  # Exit with a neutral exit code
          fi
          
      - name: Run Your Workflow Steps
        run: |
          python -m pip install pyTermTk
          python -m pip install PyYAML
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python_ci:fromkkryuu
        env:
          DOCKER_CLI_CONFIG: ${{ steps.buildx.outputs.config }}
